/* ============================================================
   main.js — Initialiser
   Boots all modules in dependency order and wires shared UX:
   copy-results button, slider fill tracking, smooth nav.
   ============================================================ */

(function () {
  'use strict';

  /* ---------- Boot sequence ---------- */
  function boot() {
    /* Modules 2/3/4 must register their module1Updated listeners BEFORE
       initModule1 fires its first synchronous calc() → dispatchEvent call.
       CustomEvent dispatch is synchronous — any listener registered after
       the dispatch is missed entirely on the first render. */
    if (typeof initModule2 === 'function') initModule2();
    if (typeof initModule3 === 'function') initModule3();
    if (typeof initModule4 === 'function') initModule4();
    if (typeof initModule1 === 'function') initModule1(); // fires module1Updated last

    initCopyButton();
    initNavScroll();
  }

  /* ---------- Copy Results ---------- */
  function initCopyButton() {
    const btn = document.getElementById('copy-btn');
    const feedback = document.getElementById('copy-feedback');
    if (!btn) return;

    btn.addEventListener('click', () => {
      const text = buildResultsText();
      navigator.clipboard.writeText(text).then(() => {
        feedback.textContent = 'Results copied to clipboard!';
        feedback.style.opacity = '1';
        setTimeout(() => { feedback.style.opacity = '0'; }, 3000);
      }).catch(() => {
        /* Fallback for older mobile browsers */
        const ta = document.createElement('textarea');
        ta.value = text;
        ta.style.position = 'fixed';
        ta.style.opacity  = '0';
        document.body.appendChild(ta);
        ta.select();
        document.execCommand('copy');
        document.body.removeChild(ta);
        feedback.textContent = 'Results copied!';
        feedback.style.opacity = '1';
        setTimeout(() => { feedback.style.opacity = '0'; }, 3000);
      });
    });
  }

  function fmt(n) {
    if (!isFinite(n) || n < 0) return '$0';
    return Math.round(n).toLocaleString('en-US', {
      style: 'currency', currency: 'USD', minimumFractionDigits: 0, maximumFractionDigits: 0
    });
  }

  function buildResultsText() {
    const lines = ['LayoffCalc.com — Your Layoff Financial Summary', '='.repeat(48), ''];

    /* Module 1 */
    const sevTypical = document.getElementById('sev-typical-gross');
    const sevNet     = document.getElementById('sev-typical-net');
    if (sevTypical) {
      lines.push('SEVERANCE ESTIMATOR');
      lines.push(`  Typical gross severance: ${sevTypical.textContent}`);
      lines.push(`  Typical net severance:   ${sevNet ? sevNet.textContent : ''}`);
      lines.push('');
    }

    /* Module 2 */
    const runway = document.getElementById('runway-headline');
    const uiNote = document.getElementById('runway-ui-note');
    if (runway) {
      lines.push('FINANCIAL RUNWAY');
      lines.push(`  ${runway.textContent}`);
      if (uiNote) lines.push(`  ${uiNote.textContent}`);
      lines.push('');
    }

    /* Module 3 */
    const cobraPrice = document.getElementById('cobra-price');
    const acaPrice   = document.getElementById('aca-price');
    if (cobraPrice) {
      lines.push('HEALTH INSURANCE');
      lines.push(`  COBRA cost:          ${cobraPrice.textContent}/mo`);
      lines.push(`  ACA Marketplace est: ${acaPrice ? acaPrice.textContent : ''}/mo`);
      const savings = document.getElementById('cobra-savings');
      if (savings) lines.push(`  ${savings.textContent}`);
      lines.push('');
    }

    /* Module 4 */
    const uiBen  = document.getElementById('ui-weekly-benefit');
    const uiDur  = document.getElementById('ui-duration');
    const uiTot  = document.getElementById('ui-total-payout');
    if (uiBen) {
      lines.push('UNEMPLOYMENT INSURANCE');
      lines.push(`  Your estimated weekly benefit: ${uiBen.textContent}`);
      lines.push(`  Maximum duration:              ${uiDur ? uiDur.textContent : ''}`);
      lines.push(`  Total maximum payout:          ${uiTot ? uiTot.textContent : ''}`);
      lines.push('');
    }

    lines.push('─'.repeat(48));
    lines.push('Generated by LayoffCalc.com — free, no account required.');
    lines.push('Not financial or legal advice. Consult a professional.');

    return lines.join('\n');
  }

  /* ---------- Smooth active-section nav ---------- */
  function initNavScroll() {
    /* Highlight active module in nav on scroll */
    const sections = document.querySelectorAll('.module-section[id]');
    if (!sections.length) return;

    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        const link = document.querySelector(`.nav-module-link[href="#${entry.target.id}"]`);
        if (!link) return;
        if (entry.isIntersecting) {
          link.classList.add('active');
        } else {
          link.classList.remove('active');
        }
      });
    }, { rootMargin: '-30% 0px -60% 0px' });

    sections.forEach(s => observer.observe(s));
  }

  /* ---------- Entry point ---------- */
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', boot);
  } else {
    boot();
  }
})();
